import Head from "next/head";
import { Geist, Geist_Mono } from "next/font/google";
import PokemonCard from "@/components/PokemonCard";
import { Box, Grid, GridItem } from "@chakra-ui/react";
import { getAllPokemons } from "@/lib/pokemon";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function HomePage({ data }) {
  return (
    <>
      <Head>
        <title>PokeMon Explorer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Box
          width={"100%"}
          bgImage="url('/forest.jpg')"
          bgPosition="center"
          bgSize="contain"
          bgRepeat="repeat-y"
          zIndex={-1}
        >
          <Box
            width="100%"
            height="100%"
            zIndex={1}
            backgroundColor="rgba(235, 235, 235, 0.3)"
            py={8}
          >
            <Grid
              templateColumns={{
                base: "repeat(3, 1fr)",
                md: "repeat(4, 1fr)",
                lg: "repeat(5, 1fr)",
              }}
              gap="6"
              mx="auto"
              width={"90%"}
            >
              {data.map((pokemon) => (
                <GridItem key={pokemon.id}>
                  <PokemonCard data={pokemon} />
                </GridItem>
              ))}
            </Grid>
          </Box>
        </Box>
      </main>
    </>
  );
}

export async function getServerSideProps() {
  let result = (await getAllPokemons()) || [];
  return {
    props: {
      data: result,
    },
  };
}
