import Head from "next/head";
import Image from "next/image";
import { Geist, Geist_Mono } from "next/font/google";
import PokemonCard from "@/components/PokemonCard";
import { Box, Container, Grid, GridItem, Stack } from "@chakra-ui/react";
import { getAllPokemons } from "@/lib/pokemon";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function HomePage({ data }) {
  // console.log("data", data);
  return (
    <>
      <Head>
        <title>PokeMon Explorer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Box width={"100%"} bg="red.300" py={"4"}>
          <Grid
            templateColumns={{
              base: "repeat(2, 1fr)",
              md: "repeat(3, 1fr)",
              lg: "repeat(4, 1fr)",
            }}
            gap="6"
            mx="auto"
            width={"90%"}
          >
            {data.map((pokemon) => (
              <GridItem key={pokemon.id}>
                <PokemonCard data={pokemon} />
              </GridItem>
            ))}
          </Grid>
        </Box>
      </main>
    </>
  );
}

export async function getServerSideProps() {
  let result = (await getAllPokemons()) || [];
  return {
    props: {
      data: result,
    },
  };
}
